version: '3'
services:
  base:
    container_name: nest-gpu
    build:
      context: .
      args:
        USERNAME: "dev"
        UID: $UID
        GID: $GID
        GIT_USER: $GIT_USER
        GIT_TOKEN: $GIT_TOKEN
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    tty: true
    volumes:
      - ..:/home/dev/nest-gpu
